### ISSUE TITLE
NameError: name 'requests' is not defined in __main__.py

### ISSUE THREAD

**Issue by shaiksamad** [fsoubelet/InstaSave#26]
`requests` module is not imported in `__main__.py` file. This causes error.

**Comment by fsoubelet** [comment]
Hi @shaiksamad thanks for noticing and reporting. There's a new version out now with a fix.

**Comment by shaiksamad** [comment]
Could you please tell me, where can I find the new version?

**Comment by fsoubelet** [comment]
Hi again @shaiksamad, it's uploaded to `PypI` so if you `python -m pip install --upgrade instasave` you will get the new version.
